# Install and test

name: Python package

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - '3.10'
                    - '3.11'
                    - '3.12'
                    - '3.13'
        steps:
            - uses: actions/checkout@v5
            - name: Install uv
              uses: astral-sh/setup-uv@v6
            - name: Install Python ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}
            - name: Install dependencies
              run: uv pip install -r dev-requirements.txt .[dev]
            - name: Run ruff QA checks
              run: python -m ruff check .
            - name: Check formatting
              run: python -m ruff format . --check
            - name: Check static typing
              run: python -m mypy lazyscribe_joblib
            - name: Run unit testing
              run: python -m pytest tests --ignore=tests/test_lazyscribe_integration --cov=./ --cov-report=xml
            - name: Run integration testing
              run: python -m pytest tests/test_lazyscribe_integration
            - name: Run Codecov
              uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                fail_ci_if_error: true
                files: ./coverage.xml
                verbose: true
